import type { ArticleSection } from "@/lib/articles";

export const revisedArticleBodies: Record<string, ArticleSection[]> = {
  aiTools: [
    { heading: "Choose a workflow before choosing a tool", paragraphs: ["Artificial intelligence is no longer useful only to large companies with dedicated technical teams. Small businesses can use it to prepare marketing material, summarize documents, organize information, automate repetitive tasks, and assist employees with everyday decisions.", "The useful starting point is a specific business problem, not a broad product list. A writing assistant may not be the right system for customer inquiries, and an automation platform may need carefully defined rules before it can safely move information between applications."], blockquote: "This comparison is based on official product documentation reviewed on October 9, 2026. It is not a hands-on benchmark, sponsored ranking, or claim that every feature was personally tested." },
    { heading: "Quick comparison: which AI tool fits your business?", paragraphs: ["These products overlap in places, but they are not direct substitutes. Match the tool to the primary job your team needs to improve."], list: ["ChatGPT — flexible general assistance for drafting, analysis, and structured work.", "Claude — document-heavy writing, analysis, and review workflows.", "Notion AI — finding and working with information held in a shared workspace.", "Zapier — connecting apps and automating repeatable operational workflows.", "Canva — creating marketing visuals and related draft copy."] },
    { heading: "1. ChatGPT: general AI assistance for everyday business work", paragraphs: ["ChatGPT can help small businesses work with text, research questions, files, and analytical tasks. The capabilities available depend on the account, plan, and product configuration.", "A repair business, for example, can turn a verified document covering its hours, booking rules, service area, and cancellation policy into a first customer FAQ. An employee should still check every generated answer against the actual policy before it is published.", "Other practical uses include organizing meeting notes into an action list, drafting a first version of customer communications, summarizing a spreadsheet, explaining technical concepts, and preparing internal procedures for human review."], list: ["Best fit: small teams that need one flexible assistant for several text, analysis, and knowledge-work tasks.", "Published business pricing lists Standard seats at $20 per user/month when billed annually or $25 monthly, with a two-seat minimum; confirm current regional pricing before purchase.", "OpenAI states that ChatGPT Business workspace data is excluded from model training by default, but businesses should still verify plan, access, and data settings before uploading confidential material."], links: [{ label: "OpenAI business pricing", href: "https://openai.com/business/pricing/" }, { label: "Managing data and privacy in ChatGPT Business", href: "https://help.openai.com/en/articles/8798634-managing-data-sharing-and-privacy-in-chatgpt-business" }] },
    { heading: "2. Claude: writing, analysis, and document-centered workflows", paragraphs: ["Claude is an AI assistant from Anthropic that supports writing, reasoning, document analysis, coding assistance, and other knowledge-work tasks. It is worth evaluating where employees regularly read detailed proposals, reports, policies, or research material.", "A small consulting company could ask it to extract deliverables, deadlines, assumptions, and open questions from a proposal into a review table. The original proposal remains authoritative, and a human reviewer should check that no clause has been omitted or misinterpreted."], list: ["Best fit: teams working frequently with proposals, policies, research, and other substantial documents.", "Anthropic publishes Free, Pro, Team, and Enterprise options. Its listed Pro price is $20/month with an annual option; team pricing and seat minimums differ.", "Claude can still misinterpret complex material or generate confident errors. Results depend on the model, prompt, supplied material, settings, and review criteria."], links: [{ label: "Anthropic pricing and available plans", href: "https://www.anthropic.com/pricing" }] },
    { heading: "3. Notion AI: workspace knowledge and project organization", paragraphs: ["Notion combines documents, databases, notes, and project workflows in a shared workspace. Its AI features are most useful when a team already maintains reasonably structured, current information there or in supported connected systems.", "A digital agency might use Notion AI to locate and summarize client onboarding procedures, project requirements, and meeting notes before a client call. The project manager should still check the original records before making a commitment."], list: ["Best fit: teams already managing documentation, projects, and internal knowledge in Notion.", "Notion says comprehensive AI features are available on Business and Enterprise plans; Free and Plus users receive limited complimentary responses for evaluation.", "Outdated documents, conflicting records, and poor permission management reduce the value and reliability of workspace answers."], links: [{ label: "Notion AI feature guide", href: "https://www.notion.com/help/notion-ai-faqs" }, { label: "Notion pricing", href: "https://www.notion.com/pricing" }] },
    { heading: "4. Zapier: automating repetitive business workflows", paragraphs: ["Zapier connects applications and lets teams create automated workflows. Its central value is reducing repetitive transfers of information and triggering approved actions between systems; not every useful automation needs AI.", "A service business could detect a website form submission, create a CRM record, notify the sales team, and start an approved follow-up workflow. Before activation, test duplicates, missing fields, failures, and recovery procedures."], list: ["Best fit: businesses repeatedly copying information between applications or performing predictable administrative work.", "Zapier's documented Free plan includes 100 tasks per month, two-step Zaps, a 15-minute polling interval where applicable, and one user. Estimate real task volume before choosing a plan.", "Automation can reproduce errors efficiently. Incorrect triggers, incomplete data, or inappropriate permissions can create operational problems."], links: [{ label: "Zapier pricing", href: "https://zapier.com/pricing" }, { label: "What is included in Zapier's Free plan?", href: "https://help.zapier.com/hc/en-us/articles/32337438839565-What-s-included-in-Zapier-s-Free-plan" }] },
    { heading: "5. Canva: AI-assisted marketing and design", paragraphs: ["Canva combines templates, editing tools, and AI-assisted creative features. It can help a small business produce social graphics, promotional posters, presentations, product announcements, and basic marketing documents without a dedicated design department.", "For example, a neighborhood cafe can create a seasonal-menu promotion using its approved logo, brand colors, actual product photography, and verified offer details. AI can assist with early copy or layout ideas, but the finished design still needs accuracy and brand review."], list: ["Best fit: small businesses that create frequent marketing visuals without needing a full professional design-production environment.", "Canva distinguishes limited free AI usage from expanded paid features. Verify current plan limits and commercial-use terms before distributing AI-created materials.", "Generated imagery may not accurately represent an actual product or service. For real advertising, business-owned photography is often preferable."], links: [{ label: "Canva pricing", href: "https://www.canva.com/pricing/" }, { label: "Magic Write documentation", href: "https://www.canva.com/help/about-magic-write/" }, { label: "Using Magic Studio safely and legally", href: "https://www.canva.com/help/using-magic-studio-safely-and-legally/" }] },
    { heading: "Pricing: budget for a pilot, not an entire AI stack", paragraphs: ["There is no universal AI budget for a small business. Start with one workflow and compare the subscription cost with the time actually saved, including correction and review work.", "As an illustrative—not observed—five-person service-business pilot, a $25 AI subscription, $60 of onboarding and review time, and $15 of additional automation usage would total $100 per month. An apparently inexpensive tool becomes costly if employees spend more time correcting work than they save."], list: ["Check per-user charges, seat minimums, usage limits, task consumption, and annual-versus-monthly terms.", "Treat vendor prices and included features as changeable; confirm them in the official links before approving spend.", "Measure results from actual work, rather than estimated savings in marketing material."] },
    { heading: "A practical 30-day AI adoption plan", paragraphs: ["Week 1: choose one repeated task with an objective success measure. Record the current hand-off, the information that may safely be shared, and the consequence of a bad result.", "Week 2: run a controlled pilot using approved, non-sensitive sample data. Keep a human accountable for the output and record failed attempts as well as successes.", "Week 3: measure task time, correction time, errors, missing information, adoption friction, operating costs, and employee feedback. Use evidence from the pilot, not projected savings.", "Week 4: continue only if the result has acceptable cost and risk. Document who may use the tool, when human review is required, and what to do if the service is unavailable."] },
    { heading: "Risks small businesses should not ignore", paragraphs: ["Do not upload customer records, payment information, credentials, or confidential agreements without verifying vendor processing terms, workspace permissions, retention settings, and applicable legal obligations. Business plans can have different controls from consumer accounts.", "AI output can omit requirements or state unsupported details. Fact-check business-critical communications and independently review calculations. Automation can also create duplicate records, send incorrect notices, or move data to inappropriate systems.", "Before building an essential process around one service, check export options, account recovery, usage limits, and fallback procedures. The business should still be able to operate during a vendor outage."], list: ["Data confidentiality: define what is prohibited, allowed, or requires approval.", "Incorrect output: keep a human reviewer for decisions, commitments, calculations, and customer-facing content.", "Automation mistakes: test realistic exceptions, failure notices, and recovery paths.", "Vendor dependence: retain exports, owned account recovery, and a non-AI fallback for essential work."] },
    { heading: "Frequently asked questions", paragraphs: ["What is the best free AI tool for a small business? There is no universal winner. Several vendors provide free access or limited trials, but the relevant limits differ. Choose the tool that supports a real workflow and verify its current restrictions.", "Can a small business use AI without technical knowledge? Yes. Many assistants and design tools target nontechnical users, while more complex automation, integrations, and data-management work can require additional expertise.", "Can AI replace a customer-support team? It may help draft responses, retrieve approved information, classify inquiries, and route requests. It should not be assumed capable of handling every exception, refund, complaint, or sensitive interaction without human oversight.", "Should a business subscribe to several AI tools? Not necessarily. Start with one or two distinct, measurable problems; add subscriptions only when they demonstrate separate value.", "How often should AI comparisons be updated? Review them when features, pricing, terms, or availability change. Fast-moving products benefit from a visible verification date and direct official links."], blockquote: "The most valuable AI tool is the one that solves a repeatable problem without adding disproportionate cost, complexity, or risk." },
    { heading: "Methodology and disclosure", paragraphs: ["This guide was prepared from publicly accessible official vendor documentation reviewed on October 9, 2026. It considers documented functionality, suitability for common small-business workflows, plan restrictions, and operational risks.", "No hands-on comparative benchmark, paid-account testing, measured productivity experiment, or vendor sponsorship is claimed. Product pricing and availability can change after the review date. Start with one problem, protect sensitive information, measure the outcome, and expand only when the results justify it."] },
  ],
  claude: [
    { heading: "Compare the job you need done", paragraphs: ["ChatGPT and Claude are general-purpose AI assistants with capabilities that vary by plan, model, region, settings, and release. The useful comparison is not a universal winner. It is whether each product handles your representative task, inputs, privacy expectations, and review process in a way your team can support.", "Use the vendors' current documentation to verify available tools before purchasing or publishing a feature comparison. OpenAI documents ChatGPT capabilities such as writing, file analysis, image input, search, and data analysis where available. Anthropic documents Claude's text, code, and image capabilities."], list: ["Bring a real but non-sensitive writing task.", "Try a structured analysis task with clear acceptance criteria.", "Check how each service handles files, citations, and corrections.", "Document plan, model, and date when recording results."] },
    { heading: "Run a fair, reproducible trial", paragraphs: ["Use the same prompt, background material, and grading rubric for both tools. Score factual support, instruction-following, useful structure, required edits, and policy fit. Do not treat a fluent answer as evidence of accuracy; independently verify material claims and calculations.", "A short trial should include failure cases: ambiguous instructions, incomplete context, requests that should be refused, and content that needs a source. Keep outputs out of customer-facing systems until an accountable reviewer has approved them."], code: "Trial record\nTask: ____________________\nPlan/model/date: __________\nInputs permitted: __________\nHuman reviewer: __________\nObserved limits: __________" },
    { heading: "Decision guide", paragraphs: ["Choose the option that meets your workflow requirements with the least operational complexity, not the one with the most marketing claims. Revisit the decision when models, prices, controls, or usage patterns change. This article does not report a head-to-head benchmark or personal testing result."], blockquote: "A comparison remains useful only when its plan, model, settings, and verification date are visible." },
  ],
  windows: [
    { heading: "Check the simple causes first", paragraphs: ["A slow Windows PC can be constrained by startup programs, low free storage, pending updates, malware, failing hardware, or a workload that exceeds the device's capacity. Change one thing at a time so you can tell what helped. Back up important files before troubleshooting, and do not download registry cleaners or unknown 'speed-up' utilities."], list: ["Restart the PC and note whether the issue returns.", "Install Windows and optional driver updates from Windows Update.", "Run a Windows Security scan.", "Check available storage in Settings > System > Storage."] },
    { heading: "Reduce startup and storage pressure", paragraphs: ["Open Task Manager with Ctrl+Shift+Esc and review the Startup apps list. Disable only programs you recognise and do not need immediately after sign-in; avoid disabling security software or hardware utilities unless you understand their purpose. In Storage settings, review temporary files and Storage Sense before deleting anything.", "Microsoft's current Windows performance guidance also covers updates, malware scans, storage, startup apps, and visual effects. Menu names can differ between Windows versions, so use Microsoft's support page for the current steps."], code: "# Open Startup apps settings\nstart ms-settings:startupapps" },
    { heading: "Know when software fixes are not enough", paragraphs: ["If the PC remains slow with few startup apps, adequate free space, current updates, and no detected malware, record CPU, memory, disk, and network use in Task Manager while the problem occurs. Repeated high disk use, hardware errors, battery swelling, crashes, or unexpected fan noise need vendor support or qualified repair. Do not defragment solid-state drives manually; Windows manages storage maintenance."], blockquote: "Measure the bottleneck before buying software or hardware." },
  ],
  codingTools: [
    { heading: "Build a small toolchain around the work", paragraphs: ["A productive developer setup usually needs an editor, version control, a runtime or compiler, dependency management, formatting or linting, tests, and a debugger. The right choices depend on language, team policy, target platform, and repository requirements. A free tool is not automatically low-cost if it adds maintenance, security review, or incompatible configuration."], list: ["Use the repository's documented runtime and package manager.", "Turn on the team's formatter and linter before making broad changes.", "Keep source control history readable with focused commits.", "Prefer built-in tools before adding extensions."] },
    { heading: "Evaluate tools with a real project", paragraphs: ["Try an editor or extension in a disposable branch on a representative repository. Verify language support, debugging, test integration, remote-development needs, accessibility, telemetry settings, update policy, and licence. Visual Studio Code's documentation describes editor features and extension management, but individual extensions are independently maintained and need their own review."], code: "# Before adding a tool, capture the baseline\nnode --version\nnpm --version\ngit status --short" },
    { heading: "Keep the setup maintainable", paragraphs: ["Pin project dependencies in the repository rather than relying on a personal global setup. Document required extensions and commands in the README, review permissions before installing extensions, and remove tools that duplicate existing capability. A smaller documented toolchain is easier for a new contributor to reproduce."], blockquote: "Choose tools that improve a repeatable workflow, not tools that merely add options." },
  ],
  rag: [
    { heading: "RAG connects a model to selected context", paragraphs: ["Retrieval-augmented generation (RAG) is a pattern in which an application retrieves relevant material and sends that material with the user's question to a language model. It does not retrain the model on every document. Microsoft Learn describes common implementations that prepare data, split it into chunks, create embeddings, retrieve relevant chunks, and then generate a response using that context."], list: ["Choose authoritative source documents.", "Extract and clean text with ownership and access controls.", "Chunk material so retrieval can return focused context.", "Retrieve, cite, evaluate, and monitor answers."] },
    { heading: "A practical support example", paragraphs: ["Imagine a support assistant for an internal product manual. When a user asks how to reset a setting, the system should retrieve the current manual section, identify the version, and show the source link alongside a concise answer. If retrieval finds weak or conflicting evidence, the assistant should say so or hand the question to support instead of filling gaps with confidence."], code: "question -> retrieve approved passages -> rank -> answer with citations\n                         |\n                         -> low confidence: ask for clarification or escalate" },
    { heading: "Limitations to design for", paragraphs: ["RAG can improve grounding, but it cannot make a weak document set correct, current, or safe. Retrieval can miss relevant material; a model can still misread supplied context; and permission boundaries matter as much as relevance. Test with known questions, measure citation quality, log failures safely, and give content owners a way to update the knowledge base."], blockquote: "Retrieval quality and source governance are product requirements, not implementation details." },
  ],
  security: [
    { heading: "Make account takeovers harder", paragraphs: ["Start with the accounts that can reset other accounts or expose money, identity documents, work systems, or personal messages. Use a different password for every account; a password manager can generate and store those passwords. NIST guidance discusses password managers, multi-factor authentication, and the risks created when credentials are reused."], list: ["Secure your primary email account first.", "Use unique passwords instead of variations on one password.", "Turn on multi-factor authentication where it is offered.", "Save recovery codes in a safe place that is not the same inbox you are protecting."] },
    { heading: "Prefer phishing-resistant options when available", paragraphs: ["Not every second factor offers the same protection. NIST describes phishing-resistant authentication as preventing an attacker posing as a service from obtaining a usable authenticator output; WebAuthn-based authenticators are an example of verifier name binding. Check whether a service supports passkeys or security keys, then follow that service's recovery guidance before removing an existing sign-in method."], list: ["Verify the site address before entering a password or approval code.", "Treat unexpected login prompts and recovery messages as suspicious.", "Review active sessions and recovery methods after a suspected compromise.", "Contact the service through its known support path, not a link in an unsolicited message."] },
    { heading: "Have a recovery plan", paragraphs: ["Record which accounts use which recovery channels. If you think an account was taken over, change the password from a trusted device, revoke unfamiliar sessions, review forwarding rules and payment details, and use the provider's documented recovery process. This is general information; high-risk accounts or an active incident may need specialist help."], blockquote: "The recovery email account deserves the strongest protection in your account set." },
  ],
  vscode: [
    { heading: "Choose extensions for a specific gap", paragraphs: ["Extensions can add language support, linting, formatting, test integration, source control views, and other workflow features. Start with the extension recommendations documented by the project's maintainers, then use the Visual Studio Code Marketplace and extension documentation to verify publisher, permissions, compatibility, update cadence, and privacy details."], list: ["Install one extension to solve one identified problem.", "Read the publisher and repository information.", "Check Workspace Trust and extension permissions.", "Test in a non-critical workspace before adopting it team-wide."] },
    { heading: "A sensible starter checklist", paragraphs: ["For many projects, the useful categories are language support, a formatter, a linter, test integration, and version-control assistance. The specific extension names should come from the project's stack and its current documentation, not from a generic list. An extension that conflicts with a repository's formatter or adds overlapping automation can create more noise than value."], code: "# Record team-required extensions in the repository\ncode --list-extensions\n# Review the output before copying it into documentation" },
    { heading: "Keep the editor trustworthy", paragraphs: ["Update VS Code and extensions regularly, disable unused extensions, and use Workspace Trust for unfamiliar repositories. Review an extension after a major update or ownership change. This article is a selection guide, not an endorsement or security assessment of a particular extension."], blockquote: "The best extension is one the team can explain, reproduce, and maintain." },
  ],
  hosting: [
    { heading: "Define the workload before comparing plans", paragraphs: ["A hosting choice starts with the site: static files, a server-rendered app, a database-backed service, or a mix. Write down expected traffic patterns, required regions, runtime version, build time, storage, backups, deployment workflow, support needs, and spending limits. Without those constraints, a provider comparison becomes a list of marketing claims."], list: ["Which parts of the site need a server at request time?", "Where are visitors and data located?", "What is the rollback and backup plan?", "Who will respond to an outage or failed deploy?"] },
    { heading: "Compare the operational details", paragraphs: ["Read each provider's current pricing, service limits, support policy, documentation, and terms. Check what happens when traffic spikes, a build fails, a limit is exceeded, or a dependency needs an update. For a Next.js site, verify supported Node and framework versions, image handling, environment-variable controls, logs, redirects, caching, and deployment preview workflow."], list: ["Use a staging or preview deployment before moving a production domain.", "Test a rollback rather than assuming one exists.", "Price the expected workload and a higher-traffic scenario.", "Document account ownership and recovery contacts."] },
    { heading: "Avoid irreversible decisions", paragraphs: ["Keep the domain, source repository, content exports, and environment-variable inventory under the publisher's control. Prefer a deployment process that another team member can reproduce. This guide does not recommend a provider because suitability depends on the verified requirements above."], blockquote: "A cheap plan is expensive if no one can restore the site when it fails." },
  ],
  productivity: [
    { heading: "Choose a workflow before choosing an app", paragraphs: ["A productivity app is useful when it supports a small repeatable practice: capture work, decide what matters, schedule or sequence it, and review commitments. Before comparing products, write down where tasks enter your system, who shares them, which devices matter, and what information must stay private. A feature list cannot decide those questions for you."], list: ["Capture new work in one dependable place.", "Separate a next action from a vague project idea.", "Review commitments on a regular cadence.", "Use notifications deliberately rather than leaving every alert on."] },
    { heading: "Test the smallest viable setup", paragraphs: ["Try a candidate app with a real week of work, not an empty demo. Add recurring obligations, a project with several steps, a shared request if collaboration matters, and one interruption. Measure whether the system makes the next action clearer. If it creates duplicate lists or demands constant restructuring, simplify before migrating more information."], code: "Weekly review\n1. Clear inboxes\n2. Confirm deadlines\n3. Choose next actions\n4. Remove stale tasks\n5. Plan focused time" },
    { heading: "Protect portability and attention", paragraphs: ["Check export options, account recovery, offline behaviour, device support, sharing controls, pricing, and data policy before committing important work. The best app is often the one your team will still use after the novelty fades. This is a decision framework, not a ranked product review."], blockquote: "A system you review consistently is more valuable than a feature-rich system you avoid." },
  ],
  apis: [
    { heading: "An API is an agreed interface", paragraphs: ["An application programming interface defines how one piece of software can ask another for a capability or data. MDN describes APIs as constructs that make complex functionality easier to use by exposing an interface instead of every implementation detail. On the web, an HTTP API commonly receives a request and returns a response with a status code, headers, and a body."], code: "GET /api/articles/42 HTTP/1.1\nAccept: application/json\n\nHTTP/1.1 200 OK\nContent-Type: application/json\n\n{ \"id\": 42, \"title\": \"Example\" }" },
    { heading: "Follow one request from start to finish", paragraphs: ["A client first chooses an endpoint and method, then sends required parameters and authentication. The server validates the request, performs the allowed work, and returns a success or error response. A useful API client handles both expected results and failures: invalid input, missing permission, rate limits, timeouts, and unavailable services."], list: ["Use HTTPS and keep secrets out of browser code.", "Read the endpoint's authentication and rate-limit rules.", "Check status codes before assuming a JSON body is successful.", "Log safe diagnostic context, never credentials or personal data."] },
    { heading: "Build a safe first integration", paragraphs: ["Start with a read-only endpoint in a test environment. Store secrets in the platform's environment-variable system, use the vendor's documented SDK or HTTP specification, and add timeouts and clear error messages. Webhooks are different: your application receives an event, so verify signatures and design processing to tolerate retries and duplicate deliveries."], blockquote: "An integration is complete only when its error and security paths are designed too." },
  ],
  wordpress: [
    { heading: "Make the problem reproducible before changing the site", paragraphs: ["WordPress errors can come from plugins, themes, caching, server configuration, updates, permissions, or a service outside WordPress. Record the exact message, URL, time, recent changes, affected users, and browser/device. Take a current backup and confirm how to restore it before disabling or updating anything on a production site."], list: ["Check the site's status and recent update history.", "Reproduce the issue in a private browser window if appropriate.", "Review error logs through the host or WordPress debugging process.", "Make one change at a time and record the result."] },
    { heading: "Isolate plugins and themes safely", paragraphs: ["WordPress's troubleshooting documentation recommends controlled isolation of plugins and themes. Prefer a staging site or maintenance window for a production property. If disabling a plugin resolves the issue, update, replace, or contact its maintainer rather than immediately reinstalling WordPress. Preserve settings and data before removing an extension."], code: "# Do not run this on production without a backup and maintenance plan.\n# Use your host's staging environment to test plugin/theme changes first." },
    { heading: "Prevent recurring incidents", paragraphs: ["Keep WordPress core, themes, plugins, PHP, and backups on a documented maintenance schedule. Limit administrator accounts and unused plugins, use trusted sources, and test updates on staging when the site is important. If an error involves payment, personal data, malware, or server compromise, use the host's incident process or qualified support."], blockquote: "A backup is useful only when restoration has been tested." },
  ],
  aiSoftware: [
    { heading: "Look for workflow changes, not slogans", paragraphs: ["AI features can change how software helps users search, draft, classify, summarise, and automate routine steps. That does not mean every feature improves a product. Product teams need to identify the user decision or task, define acceptable error rates, and design a human fallback. A generated answer that sounds convincing can still be incomplete or wrong."], list: ["Choose a narrow user problem.", "Decide which inputs are permitted.", "Define review, correction, and escalation paths.", "Measure outcomes that matter to users, not only model output volume."] },
    { heading: "Design for evidence and control", paragraphs: ["For high-impact workflows, show relevant source material, make uncertainty visible, and let users correct or reject output. Keep an audit trail appropriate to the risk, protect sensitive data, and test the system with edge cases. OpenAI and Anthropic both publish product documentation, but product capabilities, controls, and limits change; teams should verify the current documentation for the exact service and plan they use."], code: "User request -> policy check -> retrieve approved context -> draft output\n                                      |\n                                      -> cite, review, correct, or escalate" },
    { heading: "What developers can contribute", paragraphs: ["Developers can make AI features more dependable by defining interfaces, evaluation cases, monitoring, access controls, rate limits, and fallbacks. The durable work is not just prompting: it is product judgment, data governance, reliability, and user experience. This article is an engineering framework, not a forecast or a claim about industry-wide adoption."], blockquote: "Useful AI software makes the next responsible action clearer." },
  ],
};

/** Product names below are examples to evaluate, never rankings or claimed tests. */
export const editorialExpansions: Record<string, ArticleSection[]> = {
  claude: [
    { heading: "What a useful comparison can and cannot say", paragraphs: ["ChatGPT and Claude both document assistance with language and coding tasks, but a plan, model, region, account setting, and release date can change the available experience. A responsible comparison names those conditions and measures a narrow task; it does not infer that one assistant is better for every reader."], list: ["Use ChatGPT documentation to check currently available tools for the plan being considered.", "Use Anthropic documentation to check Claude's current capabilities and limits.", "Keep confidential material out of an evaluation unless the owner has approved the account and data terms.", "Repeat the same test after a meaningful product change before relying on old results."] },
    { heading: "Score the output, not the brand", paragraphs: ["A simple rubric can award points for following the brief, flagging uncertainty, preserving required facts, producing a usable format, and reducing reviewer edits. Keep the original prompt and source material so another editor can repeat the exercise. If neither result is safe enough without extensive correction, the answer may be to keep the work human-led."], links: [{ label: "Evaluating AI tools for a small business", href: "/article/best-ai-tools-for-small-businesses" }, { label: "How RAG changes grounded answers", href: "/article/what-is-retrieval-augmented-generation" }] },
  ],
  windows: [
    { heading: "Work through the Windows checks in order", paragraphs: ["First, save work and restart. Then open Settings > Windows Update and install available updates; Microsoft also documents optional driver updates in Windows Update. Next, open Windows Security > Virus & threat protection and run a scan. Finally, open Settings > System > Storage, review temporary files, and use Storage Sense only after checking what will be removed."], list: ["Record free disk space before and after cleanup.", "Use Task Manager's Processes tab while the slowdown is happening, rather than guessing which app is responsible.", "In Startup apps, disable only recognised non-essential apps and restart to test.", "If a recent app or driver coincides with the issue, use the vendor's documented uninstall or rollback path."] },
    { heading: "Avoid common false fixes", paragraphs: ["Do not install registry cleaners, driver-updater bundles, or ‘RAM boosters’ because an advert promises a speed increase. Do not manually defragment an SSD. If diagnostics show persistent hardware symptoms, back up data and use the device maker's support path rather than repeatedly changing Windows settings."], links: [{ label: "Protect online accounts after a suspicious download", href: "/article/how-to-protect-your-online-accounts" }] },
  ],
  codingTools: [
    { heading: "A concrete free baseline", paragraphs: ["A conventional starting point is Visual Studio Code for editing, Git for version control, the runtime named by the repository, and project-local commands for formatting, linting, testing, and debugging. ESLint and Prettier are examples of tools a JavaScript project may already use; do not add them just because another project does. The repository's package manifest and contributor documentation are the source of truth."], list: ["Editor: use a maintained editor with language support for the project.", "Version control: use Git and the repository's review workflow.", "Quality checks: run the project's formatter, linter, type check, and tests.", "Debugging: start with the runtime and framework's built-in tools before adding a GUI client."] },
    { heading: "Check before installing", paragraphs: ["Read the licence, publisher, permissions, update policy, and maintenance status for any extension or desktop client. Keep a note of why it was introduced and how to remove it. This avoids turning a personal preference into an undocumented team dependency."], links: [{ label: "Choosing VS Code extensions responsibly", href: "/article/best-vscode-extensions-for-developers" }, { label: "A beginner's guide to APIs", href: "/article/beginners-guide-to-apis" }] },
  ],
  rag: [
    { heading: "Build the retrieval path deliberately", paragraphs: ["A useful RAG design usually has four separate concerns: ingest approved documents, split and index them, retrieve and rank candidates for a question, and generate an answer that identifies the evidence used. Microsoft describes chunking and embeddings as common indexing steps; the exact implementation depends on the data, query patterns, and access model."], list: ["Attach source, version, owner, and permission metadata to each chunk.", "Test retrieval independently from answer writing.", "Return a source link or passage identifier when the product can safely do so.", "Set a fallback for weak evidence instead of forcing an answer."] },
    { heading: "Evaluate with questions that have known answers", paragraphs: ["Create a small evaluation set from current approved documents. Include answerable questions, ambiguous questions, questions that should be refused for access reasons, and questions where the material is missing. Review retrieved passages as well as the final response; a fluent answer is not evidence that retrieval worked."], links: [{ label: "Comparing AI assistants without a universal winner", href: "/article/chatgpt-vs-claude" }, { label: "How AI affects software design work", href: "/article/how-ai-is-changing-software-development" }] },
  ],
  security: [
    { heading: "A practical account-hardening order", paragraphs: ["Start with the email inbox used for password resets, then financial, work, cloud-storage, and messaging accounts. Use a password manager to create a distinct password for each account. Enable the strongest sign-in method that the service actually offers and make sure recovery codes and recovery contacts are current before removing an old method."], list: ["Check recovery email addresses and phone numbers.", "Remove sessions and devices you do not recognise.", "Turn on alerts for sign-ins or security changes where available.", "Store recovery codes away from the account they recover."] },
    { heading: "Treat a suspected compromise as an incident", paragraphs: ["Use a trusted device, change the affected password, revoke unfamiliar sessions, inspect forwarding rules and payment details, and follow the provider's own recovery process. Never give a one-time code to someone who contacted you unexpectedly. For a work or financial account, report the incident through the organisation or institution's known channel."], links: [{ label: "Safe WordPress troubleshooting", href: "/article/common-wordpress-errors-and-fixes" }] },
  ],
  vscode: [
    { heading: "Useful categories and examples to investigate", paragraphs: ["The most useful extensions depend on the language and repository. For a JavaScript or TypeScript project, developers often evaluate ESLint (`dbaeumer.vscode-eslint`) for lint feedback and Prettier (`esbenp.prettier-vscode`) for formatting. GitLens (`eamodio.gitlens`) is an example of an optional source-control extension. These names are examples to investigate in the Marketplace, not endorsements or a security review."], list: ["Confirm the publisher and read the Marketplace README and changelog.", "Check whether the repository already owns formatting and linting configuration.", "Install one extension at a time and test it in a non-critical workspace.", "Remove overlapping extensions when they create competing edits or notifications."] },
    { heading: "Use workspace recommendations sparingly", paragraphs: ["VS Code supports workspace extension recommendations, which can help a team document genuinely required tooling. Keep the list short and explain why each extension is needed. An individual developer can still use a personal profile for optional preferences without making that preference a project requirement."], code: "// .vscode/extensions.json\n{\n  \"recommendations\": [\"dbaeumer.vscode-eslint\"]\n}", links: [{ label: "Build a maintainable free coding toolchain", href: "/article/best-free-coding-tools" }] },
  ],
  hosting: [
    { heading: "Compare hosting models before vendors", paragraphs: ["A static site host, a managed Next.js platform, a managed WordPress host, and a general cloud provider solve different operational problems. For a Next.js application, verify Node and framework support, server-rendering needs, image handling, environment-variable controls, logs, redirects, preview deployments, and rollback procedures. For a WordPress site, confirm staging, backups, update controls, and support boundaries."], list: ["Static or mostly static site: ask about deploy previews, cache invalidation, and image delivery.", "Server-rendered app: ask about runtime limits, logs, scaling, and incident support.", "CMS site: ask about backups, staging, PHP/database compatibility, and update recovery.", "Every model: keep domain and account recovery under the publisher's control."] },
    { heading: "Run a reversible proof of concept", paragraphs: ["Use a preview or staging deployment, set only non-production environment values, deploy a small representative build, and test a rollback. Compare the provider's documented limits and current billing terms against measured build time, traffic, storage, and support needs. Do not move a production domain until those checks pass."], links: [{ label: "WordPress troubleshooting and maintenance", href: "/article/common-wordpress-errors-and-fixes" }] },
  ],
  productivity: [
    { heading: "Match an app to the shape of the work", paragraphs: ["Todoist is worth evaluating when an individual or small team needs tasks, projects, reminders, filters, and collaboration. Notion is worth evaluating when tasks need to live alongside documents and a custom project database. Neither is automatically better: compare capture speed, recurring work, collaboration, notifications, export, recovery, offline behaviour, accessibility, pricing, and data controls for your own workflow."], list: ["Personal action list: test whether new tasks are quick to capture and review.", "Shared work: test assignment, permission, comments, and hand-off clarity.", "Documentation-heavy work: test whether project context remains findable without duplicating it.", "Migration: export a small trial project before committing important work."] },
    { heading: "Run a one-week trial with an exit test", paragraphs: ["Use a real week of low-risk work and keep a simple tally: tasks captured, tasks lost, duplicated lists, unexpected notifications, and time spent maintaining the system. At the end, test export and account recovery documentation. This article does not rank apps or make a claim about current plan features; verify vendors' current help and pricing pages before choosing."], links: [{ label: "Choose a web host with a reversible trial", href: "/article/how-to-choose-a-web-hosting-provider" }, { label: "Build a lean coding workflow", href: "/article/best-free-coding-tools" }] },
  ],
  apis: [
    { heading: "Try a safe read-only request", paragraphs: ["Before adding authentication or writes, call a documented read-only endpoint in a test environment. Read the response status before parsing the body, set a timeout in the real application, and show an error that helps the user without revealing credentials. The following example illustrates the control flow; endpoint and authentication details always come from the provider's documentation."], code: "const response = await fetch(\"https://api.example.test/articles/42\");\nif (!response.ok) {\n  throw new Error(`Request failed: ${response.status}`);\n}\nconst article = await response.json();" },
    { heading: "Keep credentials and webhooks separate from browser code", paragraphs: ["A browser bundle is not a safe place for a secret API key. Put secrets in server-side environment configuration, grant only the permissions needed, and rotate or revoke a key through the provider when necessary. For webhooks, verify the provider's signature and make handlers safe to retry because delivery can be duplicated or delayed."], links: [{ label: "Build a dependable developer toolchain", href: "/article/best-free-coding-tools" }, { label: "Understand RAG application architecture", href: "/article/what-is-retrieval-augmented-generation" }] },
  ],
  wordpress: [
    { heading: "A safe procedure for a plugin or theme conflict", paragraphs: ["Do this on staging whenever possible. First take and verify a backup. Record the error, time, affected URL, and recent changes. If the dashboard is available, temporarily deactivate plugins, then reactivate them one at a time while checking the same symptom. If the problem disappears only with a default theme, document that result before contacting the theme or plugin maintainer."], list: ["Do not delete a plugin before preserving its settings and data.", "Do not test broad deactivation on a busy production store without a maintenance plan.", "Check browser console and network errors when a front-end action fails.", "Use the host's logs and WordPress Site Health information to collect evidence."] },
    { heading: "Turn a repair into a maintenance record", paragraphs: ["Write down the cause, versions, change made, rollback method, and result. Keep core, themes, plugins, PHP, and backups on an owned maintenance schedule; test updates on staging when the site matters. A white screen, a payment issue, suspected malware, or personal-data exposure should go through the host's or security provider's incident process rather than an improvised fix."], links: [{ label: "Choose a hosting provider by operational evidence", href: "/article/how-to-choose-a-web-hosting-provider" }, { label: "Protect accounts used for WordPress administration", href: "/article/how-to-protect-your-online-accounts" }] },
  ],
  aiSoftware: [
    { heading: "Where AI changes software work", paragraphs: ["AI can assist with narrow activities such as drafting text, classifying incoming work, retrieving approved knowledge, and generating a first implementation outline. The engineering question is not whether output exists; it is whether the product makes errors visible, protects permitted data, and gives a user a safe correction or escalation path."], list: ["Define the task and an unacceptable failure before choosing a model.", "Keep the source or reason for an important output visible where practical.", "Measure correction effort and harmful failures, not only how much text was generated.", "Retain a non-AI path for outages, uncertainty, or user preference where the risk warrants it."] },
    { heading: "Make evaluation part of delivery", paragraphs: ["Before release, create representative examples with expected outcomes, include edge cases and refusals, and review results whenever a model, prompt, tool, or data source changes. Product teams should record what was evaluated and what was not. This is more useful to readers than a broad prediction about which companies will ‘win’."], links: [{ label: "A practical introduction to RAG", href: "/article/what-is-retrieval-augmented-generation" }, { label: "How to compare assistants responsibly", href: "/article/chatgpt-vs-claude" }] },
  ],
};
