import type { ArticleSection } from "@/lib/articles";

export const revisedArticleBodies: Record<string, ArticleSection[]> = {
  aiTools: [
    { heading: "Choose a workflow before choosing a tool", paragraphs: ["Artificial intelligence is no longer useful only to large companies with dedicated technical teams. Small businesses can use it to prepare marketing material, summarize documents, organize information, automate repetitive tasks, and assist employees with everyday decisions.", "The useful starting point is a specific business problem, not a broad product list. A writing assistant may not be the right system for customer inquiries, and an automation platform may need carefully defined rules before it can safely move information between applications."], blockquote: "This comparison is based on official product documentation reviewed on October 9, 2026. It is not a hands-on benchmark, sponsored ranking, or claim that every feature was personally tested." },
    { heading: "Quick comparison: which AI tool fits your business?", paragraphs: ["These products overlap in places, but they are not direct substitutes. Match the tool to the primary job your team needs to improve."], list: ["ChatGPT — flexible general assistance for drafting, analysis, and structured work.", "Claude — document-heavy writing, analysis, and review workflows.", "Notion AI — finding and working with information held in a shared workspace.", "Zapier — connecting apps and automating repeatable operational workflows.", "Canva — creating marketing visuals and related draft copy."] },
    { heading: "1. ChatGPT: general AI assistance for everyday business work", paragraphs: ["ChatGPT can help small businesses work with text, research questions, files, and analytical tasks. The capabilities available depend on the account, plan, and product configuration.", "A repair business, for example, can turn a verified document covering its hours, booking rules, service area, and cancellation policy into a first customer FAQ. An employee should still check every generated answer against the actual policy before it is published.", "Other practical uses include organizing meeting notes into an action list, drafting a first version of customer communications, summarizing a spreadsheet, explaining technical concepts, and preparing internal procedures for human review."], list: ["Best fit: small teams that need one flexible assistant for several text, analysis, and knowledge-work tasks.", "Published business pricing lists Standard seats at $20 per user/month when billed annually or $25 monthly, with a two-seat minimum; confirm current regional pricing before purchase.", "OpenAI states that ChatGPT Business workspace data is excluded from model training by default, but businesses should still verify plan, access, and data settings before uploading confidential material."], links: [{ label: "OpenAI business pricing", href: "https://openai.com/business/pricing/" }, { label: "Managing data and privacy in ChatGPT Business", href: "https://help.openai.com/en/articles/8798634-managing-data-sharing-and-privacy-in-chatgpt-business" }] },
    { heading: "2. Claude: writing, analysis, and document-centered workflows", paragraphs: ["Claude is an AI assistant from Anthropic that supports writing, reasoning, document analysis, coding assistance, and other knowledge-work tasks. It is worth evaluating where employees regularly read detailed proposals, reports, policies, or research material.", "A small consulting company could ask it to extract deliverables, deadlines, assumptions, and open questions from a proposal into a review table. The original proposal remains authoritative, and a human reviewer should check that no clause has been omitted or misinterpreted."], list: ["Best fit: teams working frequently with proposals, policies, research, and other substantial documents.", "Anthropic publishes Free, Pro, Team, and Enterprise options. Its listed Pro price is $20/month with an annual option; team pricing and seat minimums differ.", "Claude can still misinterpret complex material or generate confident errors. Results depend on the model, prompt, supplied material, settings, and review criteria."], links: [{ label: "Anthropic pricing and available plans", href: "https://claude.com/pricing" }] },
    { heading: "3. Notion AI: workspace knowledge and project organization", paragraphs: ["Notion combines documents, databases, notes, and project workflows in a shared workspace. Its AI features are most useful when a team already maintains reasonably structured, current information there or in supported connected systems.", "A digital agency might use Notion AI to locate and summarize client onboarding procedures, project requirements, and meeting notes before a client call. The project manager should still check the original records before making a commitment."], list: ["Best fit: teams already managing documentation, projects, and internal knowledge in Notion.", "Notion says comprehensive AI features are available on Business and Enterprise plans; Free and Plus users receive limited complimentary responses for evaluation.", "Outdated documents, conflicting records, and poor permission management reduce the value and reliability of workspace answers."], links: [{ label: "Notion AI feature guide", href: "https://www.notion.com/help/notion-ai-faqs" }, { label: "Notion pricing", href: "https://www.notion.com/pricing" }] },
    { heading: "4. Zapier: automating repetitive business workflows", paragraphs: ["Zapier connects applications and lets teams create automated workflows. Its central value is reducing repetitive transfers of information and triggering approved actions between systems; not every useful automation needs AI.", "A service business could detect a website form submission, create a CRM record, notify the sales team, and start an approved follow-up workflow. Before activation, test duplicates, missing fields, failures, and recovery procedures."], list: ["Best fit: businesses repeatedly copying information between applications or performing predictable administrative work.", "Zapier's documented Free plan includes 100 tasks per month, two-step Zaps, a 15-minute polling interval where applicable, and one user. Estimate real task volume before choosing a plan.", "Automation can reproduce errors efficiently. Incorrect triggers, incomplete data, or inappropriate permissions can create operational problems."], links: [{ label: "Zapier pricing", href: "https://zapier.com/pricing" }, { label: "What is included in Zapier's Free plan?", href: "https://help.zapier.com/hc/en-us/articles/32337438839565-What-s-included-in-Zapier-s-Free-plan" }] },
    { heading: "5. Canva: AI-assisted marketing and design", paragraphs: ["Canva combines templates, editing tools, and AI-assisted creative features. It can help a small business produce social graphics, promotional posters, presentations, product announcements, and basic marketing documents without a dedicated design department.", "For example, a neighborhood cafe can create a seasonal-menu promotion using its approved logo, brand colors, actual product photography, and verified offer details. AI can assist with early copy or layout ideas, but the finished design still needs accuracy and brand review."], list: ["Best fit: small businesses that create frequent marketing visuals without needing a full professional design-production environment.", "Canva distinguishes limited free AI usage from expanded paid features. Verify current plan limits and commercial-use terms before distributing AI-created materials.", "Generated imagery may not accurately represent an actual product or service. For real advertising, business-owned photography is often preferable."], links: [{ label: "Canva pricing", href: "https://www.canva.com/pricing/" }, { label: "Magic Write documentation", href: "https://www.canva.com/help/about-magic-write/" }, { label: "Using Magic Studio safely and legally", href: "https://www.canva.com/help/using-magic-studio-safely-and-legally/" }] },
    { heading: "Pricing: budget for a pilot, not an entire AI stack", paragraphs: ["There is no universal AI budget for a small business. Start with one workflow and compare the subscription cost with the time actually saved, including correction and review work.", "As an illustrative—not observed—five-person service-business pilot, a $25 AI subscription, $60 of onboarding and review time, and $15 of additional automation usage would total $100 per month. An apparently inexpensive tool becomes costly if employees spend more time correcting work than they save."], list: ["Check per-user charges, seat minimums, usage limits, task consumption, and annual-versus-monthly terms.", "Treat vendor prices and included features as changeable; confirm them in the official links before approving spend.", "Measure results from actual work, rather than estimated savings in marketing material."] },
    { heading: "A practical 30-day AI adoption plan", paragraphs: ["Week 1: choose one repeated task with an objective success measure. Record the current hand-off, the information that may safely be shared, and the consequence of a bad result.", "Week 2: run a controlled pilot using approved, non-sensitive sample data. Keep a human accountable for the output and record failed attempts as well as successes.", "Week 3: measure task time, correction time, errors, missing information, adoption friction, operating costs, and employee feedback. Use evidence from the pilot, not projected savings.", "Week 4: continue only if the result has acceptable cost and risk. Document who may use the tool, when human review is required, and what to do if the service is unavailable."] },
    { heading: "Risks small businesses should not ignore", paragraphs: ["Do not upload customer records, payment information, credentials, or confidential agreements without verifying vendor processing terms, workspace permissions, retention settings, and applicable legal obligations. Business plans can have different controls from consumer accounts.", "AI output can omit requirements or state unsupported details. Fact-check business-critical communications and independently review calculations. Automation can also create duplicate records, send incorrect notices, or move data to inappropriate systems.", "Before building an essential process around one service, check export options, account recovery, usage limits, and fallback procedures. The business should still be able to operate during a vendor outage."], list: ["Data confidentiality: define what is prohibited, allowed, or requires approval.", "Incorrect output: keep a human reviewer for decisions, commitments, calculations, and customer-facing content.", "Automation mistakes: test realistic exceptions, failure notices, and recovery paths.", "Vendor dependence: retain exports, owned account recovery, and a non-AI fallback for essential work."] },
    { heading: "Frequently asked questions", paragraphs: ["What is the best free AI tool for a small business? There is no universal winner. Several vendors provide free access or limited trials, but the relevant limits differ. Choose the tool that supports a real workflow and verify its current restrictions.", "Can a small business use AI without technical knowledge? Yes. Many assistants and design tools target nontechnical users, while more complex automation, integrations, and data-management work can require additional expertise.", "Can AI replace a customer-support team? It may help draft responses, retrieve approved information, classify inquiries, and route requests. It should not be assumed capable of handling every exception, refund, complaint, or sensitive interaction without human oversight.", "Should a business subscribe to several AI tools? Not necessarily. Start with one or two distinct, measurable problems; add subscriptions only when they demonstrate separate value.", "How often should AI comparisons be updated? Review them when features, pricing, terms, or availability change. Fast-moving products benefit from a visible verification date and direct official links."], blockquote: "The most valuable AI tool is the one that solves a repeatable problem without adding disproportionate cost, complexity, or risk." },
    { heading: "Methodology and disclosure", paragraphs: ["This guide was prepared from publicly accessible official vendor documentation reviewed on October 9, 2026. It considers documented functionality, suitability for common small-business workflows, plan restrictions, and operational risks.", "No hands-on comparative benchmark, paid-account testing, measured productivity experiment, or vendor sponsorship is claimed. Product pricing and availability can change after the review date. Start with one problem, protect sensitive information, measure the outcome, and expand only when the results justify it."] },
  ],
  claude: [
    { paragraphs: ["Editorial research date: October 9, 2026", "ChatGPT and Claude are two widely used AI assistants that can help people write, research, analyze information, develop software, and handle everyday knowledge work.", "Both can turn natural-language instructions into useful results. Both can also make mistakes.", "The challenge is deciding which assistant fits your actual workflow rather than choosing one based on brand recognition, a viral demonstration, or a benchmark that may not reflect your needs.", "In this guide, we compare ChatGPT from OpenAI and Claude from Anthropic across features, writing, coding, research, document analysis, pricing, and privacy. We also explain how to test the two assistants fairly before committing to a subscription."], blockquote: "Editorial disclosure: This comparison is based on official product documentation reviewed on October 9, 2026. It does not present original hands-on benchmark results or claim that one assistant is universally more accurate than the other." },
    { heading: "ChatGPT vs Claude: Quick comparison", table: { headers: ["Category", "ChatGPT", "Claude"], rows: [["Developer", "OpenAI", "Anthropic"], ["General writing", "Supported", "Supported"], ["Document analysis", "Supported, subject to limits", "Supported, subject to limits"], ["Coding assistance", "Chat-based coding and supported coding tools", "Chat-based coding and Claude Code"], ["Web research", "Search and deep research features", "Web search and Research features"], ["Workspace organization", "Projects and other organizational tools", "Projects and organizational features"], ["File handling", "File uploads and analysis", "Document and supported file analysis"], ["Image generation", "Available through supported ChatGPT tools and plans", "Not a directly equivalent built-in image-generation workflow"], ["Business accounts", "Business and Enterprise offerings", "Team and Enterprise offerings"], ["Free access", "Available with limits", "Available with limits"]] }, paragraphs: ["Neither product should be considered the winner in every category. Performance depends on the specific model, task, inputs, plan, and settings."] },
    { heading: "1. What is ChatGPT?", paragraphs: ["ChatGPT is OpenAI's conversational AI assistant. It can help users draft and revise text, explain concepts, analyze uploaded information, write code, conduct research, and work with images.", "Depending on the subscription and available features, ChatGPT also provides tools for web search, deeper research, structured data analysis, voice interaction, and image creation."], links: [{ label: "OpenAI — ChatGPT Capabilities Overview", href: "https://help.openai.com/en/articles/9260256-chatgpt-capabilities-overview" }] },
    { heading: "Where ChatGPT can be useful", headingLevel: 3, paragraphs: ["A marketing professional might use ChatGPT to outline a campaign, rewrite messaging for different audiences, and prepare a content calendar.", "A business analyst might upload a spreadsheet and ask for a breakdown of trends, anomalies, and questions to investigate.", "A developer might use the assistant to explain unfamiliar code, troubleshoot an error, or plan a software feature.", "The practical appeal is that several different kinds of work can happen within one conversational interface."] },
    { heading: "What to keep in mind", headingLevel: 3, paragraphs: ["Not every account includes every tool, and usage allowances vary.", "ChatGPT can also misunderstand a document, generate an incorrect calculation, or provide an answer that sounds more certain than the available evidence supports.", "For important decisions, users should verify conclusions against original documents or trusted references."] },
    { heading: "2. What is Claude?", paragraphs: ["Claude is Anthropic's AI assistant. It supports writing, document analysis, software-related tasks, question answering, and other knowledge-work activities.", "Claude also offers features such as Projects, web search, Research, integrations, and Claude Code, with access dependent on the relevant plan and product."], links: [{ label: "Anthropic — Pricing and Plans", href: "https://claude.com/pricing" }, { label: "Claude — Web Search Documentation", href: "https://support.claude.com/en/articles/10684626-enable-and-use-web-search" }] },
    { heading: "Where Claude can be useful", headingLevel: 3, paragraphs: ["A consultant might ask Claude to summarize a long client proposal and extract assumptions, deadlines, and unresolved questions.", "A software engineer might use Claude to review code, explain a technical design, or work through a development task.", "A researcher might use its supported research tools to investigate a topic and organize information for further verification."] },
    { heading: "What to keep in mind", headingLevel: 3, paragraphs: ["Claude can omit details, misinterpret instructions, or state unsupported conclusions.", "When examining a contract, policy, financial document, or customer record, the original material should remain authoritative.", "Advanced features and usage limits vary across Free, Pro, Max, Team, and Enterprise offerings."] },
    { heading: "3. Which is better for writing?", paragraphs: ["Both ChatGPT and Claude can draft, edit, summarize, and restructure text.", "The most meaningful difference is often how well a specific model follows your preferred style and requirements.", "Consider a small business preparing a product announcement.", "A useful evaluation would require both assistants to use the same product facts, word limit, audience, tone, and call to action.", "Then compare their outputs for:"], list: ["Factual accuracy.", "Compliance with the supplied instructions.", "Readability and organization.", "Unnecessary marketing language.", "Editing time required.", "Consistency with the company's brand voice."], blockquote: "Practical recommendation: Choose the assistant whose drafts consistently require fewer corrections for your specific writing tasks. Do not assume that results from one model version apply permanently to every future version." },
    { heading: "4. Which is better for coding?", paragraphs: ["ChatGPT and Claude both support software-development workflows, but their development products and integrations are not identical.", "ChatGPT can explain code, assist with debugging, help design application architecture, and support coding workflows through available tools. OpenAI also offers Codex-related functionality for software-development work.", "Anthropic offers Claude Code, a developer tool designed for coding tasks within supported development environments."] },
    { heading: "A realistic coding comparison", headingLevel: 3, paragraphs: ["Suppose you maintain a Next.js website.", "Instead of asking each assistant to build an entire application, create a small, reproducible evaluation:"], orderedList: ["Provide the same repository snapshot or relevant files.", "Describe one bug with clear steps to reproduce it.", "Define what a correct fix should do.", "Require the assistant to preserve existing behavior.", "Run the same automated tests on each result.", "Compare code quality, test results, and manual corrections."], blockquote: "Practical recommendation: Evaluate the entire workflow, including IDE compatibility, repository access, security controls, testing, and cost." },
    { heading: "5. Which is better for research?", paragraphs: ["Both products provide web-enabled research capabilities, but features and availability vary.", "ChatGPT offers web search and deep research tools for applicable accounts. Claude offers web search and Research functionality within supported plans and environments.", "For research-heavy work, test citation accuracy and completeness using the same research question and a predefined evaluation checklist. Do not count citations alone; check whether each citation actually supports the claim beside it and whether the information is current."] },
    { heading: "6. Which handles documents better?", paragraphs: ["Both assistants can help users work with documents, subject to file-type support, size limits, and plan restrictions.", "Common applications include summarizing reports, extracting action items, organizing meeting notes, and comparing written requirements.", "A company reviewing a supplier agreement might ask an assistant to identify contract duration, renewal provisions, payment obligations, termination conditions, liability-related clauses, and questions requiring legal advice. This can help organize the review, but neither assistant should replace a qualified legal reviewer.", "Provide each assistant with the same document and independently verified questions. Measure correct answers, unsupported statements, omissions, and time spent checking the result."], blockquote: "Practical recommendation: Choose based on demonstrated reliability with your document types, not an unsupported claim about which assistant is better at long documents." },
    { heading: "7. ChatGPT vs Claude pricing", paragraphs: ["Both products offer free access as well as paid individual and organizational options.", "OpenAI publishes a range of individual and business plans. Free access has usage limits, while paid plans provide different combinations of model access, tools, and allowances. The exact monthly amount can depend on the plan, country, billing arrangement, and product changes.", "Anthropic publishes Free, Pro, Max, Team, and Enterprise options. Its official pricing information has listed Claude Pro at $20 per month on monthly billing, with a discounted annual arrangement. Max and organization plans have different costs and usage conditions.", "Which subscription offers better value depends on your usage. Before subscribing, calculate the cost of the tools you actually need, not just the advertised base price."], links: [{ label: "ChatGPT Pricing", href: "https://chatgpt.com/pricing/" }, { label: "Claude Pricing", href: "https://claude.com/pricing" }] },
    { heading: "8. Privacy and business data", paragraphs: ["Privacy is particularly important when employees use AI with customer information, internal documents, or proprietary code.", "Both vendors publish information about their consumer and organizational offerings, but their policies and controls are not identical across plans.", "Before adopting either product, verify:"], list: ["Whether submitted business data may be used for model improvement.", "What retention and deletion controls apply.", "Whether workspace administrators can manage access.", "Which third-party integrations can access information.", "Whether connected applications respect existing permissions.", "Whether the vendor's terms meet your legal and contractual requirements."], blockquote: "Do not assume that settings for an individual consumer account automatically apply to a business workspace. Where sensitive data is involved, obtain the required organizational and legal approvals before uploading it." },
    { heading: "9. Which should you choose? Four realistic scenarios", paragraphs: ["Scenario A: A small marketing team needs campaign drafts, performance summaries, occasional visual assets, and content ideas. Test ChatGPT's supported writing, data analysis, and creative tools, and Claude on the same writing assignments. The deciding factor should be the actual range of tools required and the time spent editing results.", "Scenario B: A consultant working with long documents should test both assistants against representative proposals, reports, and research materials, with particular emphasis on confidentiality, traceability, and correction effort.", "Scenario C: A full-stack developer should compare ChatGPT or Codex workflows and Claude or Claude Code workflows with the same repository and acceptance criteria. The quality of the completed, tested change matters more than stylistic preference.", "Scenario D: A business evaluating AI for the first time should start with accessible free options, use non-sensitive examples, and identify one measurable productivity benefit before committing to multiple subscriptions."] },
    { heading: "10. How to run your own ChatGPT vs Claude test", paragraphs: ["A short structured evaluation is more useful than asking either product which one is best.", "Choose three realistic tasks: Writing — produce a customer email from verified facts, with a specific word limit and tone. Analysis — answer ten questions about a non-sensitive report with known correct answers. Technical work — explain or fix a small code problem with a reproducible test.", "Use the same inputs for both assistants. Record the model, plan, enabled tools, test date, and whether any outside applications were connected.", "Score each result using a simple rubric:", "These scores are a suggested evaluation method, not results from testing conducted for this article. If possible, repeat important tests. AI responses can vary even with similar prompts."], table: { headers: ["Criterion", "Score"], rows: [["Accuracy", "0–5"], ["Following instructions", "0–5"], ["Completeness", "0–5"], ["Clarity", "0–5"], ["Required human corrections", "Record actual time"]] } },
    { heading: "Frequently asked questions", paragraphs: ["Is Claude better than ChatGPT for writing? Neither is universally better. Both can write and edit text. Results vary with model version, instructions, context, and the kind of writing being evaluated.", "Is ChatGPT or Claude better for programming? Both support programming tasks, and each vendor offers additional development tooling. Test them with your repository, coding requirements, and automated tests before deciding.", "Can ChatGPT and Claude access the internet? Both offer web-enabled features, subject to plan, product, location, and available settings. Access to a search tool does not guarantee that every source can be retrieved.", "Is Claude free? Claude has a free offering with usage limits. Paid tiers provide additional access and capabilities.", "Is ChatGPT free? ChatGPT also offers free access with limits. More advanced capabilities and usage allowances depend on the selected subscription.", "Can I use both ChatGPT and Claude? Yes. Some users employ both for different tasks or for cross-checking important work. However, agreement between two AI assistants is not proof that a claim is correct.", "Should a business upload confidential documents to either assistant? Only after verifying the relevant plan's privacy settings, processing terms, organizational permissions, and applicable legal requirements."] },
    { heading: "Final verdict", paragraphs: ["ChatGPT and Claude are both capable AI assistants, but choosing between them is not a simple matter of declaring one more intelligent.", "ChatGPT offers a broad collection of conversational, analytical, research, and creative capabilities through its supported tools.", "Claude offers conversational assistance, document work, research features, integrations, and dedicated coding workflows through its product ecosystem.", "The most useful decision is the one supported by your actual tasks, acceptable risks, available features, and cost.", "Before paying for either, run a short, repeatable trial and evaluate how much useful work each assistant helps you complete."] },
    { heading: "Research methodology", paragraphs: ["Verified: October 9, 2026.", "This article uses official documentation from OpenAI and Anthropic to describe available capabilities, plans, and general use cases. It does not include independent model benchmarks, controlled performance tests, invented customer testimonials, or affiliate-driven rankings.", "Product availability, pricing, model names, and usage allowances are subject to change."] },
  ],
  windows: [
    { paragraphs: ["Last researched and verified: October 9, 2026", "A slow Windows PC can turn simple tasks into frustrating experiences. Applications take longer to open, browsers become unresponsive, and even switching between windows can feel sluggish.", "The good news is that you don't always need a new computer, expensive optimization software, or a complete Windows reinstall.", "Slow performance often comes from manageable issues such as too many background applications, insufficient storage, outdated software, heavy memory usage, or an underlying hardware problem.", "This guide explains 12 practical ways to improve Windows PC performance, starting with the safest and easiest changes.", "Most instructions focus on Windows 11. Some also apply to Windows 10, although Windows 10's standard support ended on October 14, 2025."], blockquote: "Before you start: Save your open work and back up important files. Avoid third-party registry cleaners, unknown driver installers, and utilities promising dramatic one-click performance improvements." },
    { heading: "Quick diagnosis: What's making your PC slow?", paragraphs: ["Before changing settings, try to identify when the slowdown happens.", "These are possible explanations, not definitive diagnoses. A symptom can have several causes."], table: { headers: ["Symptom", "Possible cause", "First thing to check"], rows: [["Slow startup", "Too many startup apps", "Startup apps in Task Manager"], ["Browser freezes with many tabs", "Memory pressure", "Task Manager → Memory"], ["PC becomes slow while installing updates", "Background disk or CPU activity", "Windows Update and Task Manager"], ["System drive nearly full", "Insufficient free storage", "Settings → System → Storage"], ["PC slows down when unplugged", "Power-saving settings", "Settings → Power & battery"], ["Fans run constantly", "Heavy processes, dust, or cooling problems", "Task Manager and ventilation"], ["Everything is slow despite basic fixes", "Hardware, driver, or operating-system issues", "Diagnostics and device health"]] } },
    { heading: "1. Restart your computer", paragraphs: ["A proper restart is one of the simplest troubleshooting steps. It closes running programs, ends many background processes, and gives Windows a fresh start.", "If the computer becomes noticeably faster afterward but slows down again later, investigate applications that accumulate memory usage or run repeatedly in the background. A restart can relieve a symptom without fixing its underlying cause."], orderedList: ["Save your files.", "Open Start.", "Select Power.", "Choose Restart."] },
    { heading: "2. Disable unnecessary startup applications", paragraphs: ["Many applications start automatically when you sign in to Windows. Messaging tools, game launchers, update utilities, and other background programs can increase startup time and consume resources before you begin working.", "Turning off a startup app does not uninstall it. You can still open it manually. Avoid disabling antivirus software, accessibility utilities, device management tools, or unfamiliar system-related applications without understanding their purpose.", "For a laptop used mainly for web browsing and office work, reducing unnecessary startup programs may make startup smoother."] },
    { heading: "How to disable startup apps", headingLevel: 3, orderedList: ["Press Ctrl + Shift + Esc to open Task Manager.", "Select Startup apps.", "Review the list and each application's startup impact.", "Right-click an application you recognize but don't need immediately.", "Select Disable."], paragraphs: ["Alternatively, open Settings → Apps → Startup."] },
    { heading: "3. Free up storage space", paragraphs: ["Windows needs available disk space for temporary files, updates, application data, and everyday operations. When your system drive becomes very full, performance and update reliability can suffer."] },
    { heading: "Check your available storage", headingLevel: 3, paragraphs: ["Open Settings → System → Storage. Review which categories occupy the most space, such as installed apps, temporary files, documents, and other files."] },
    { heading: "Use Windows Storage Sense", headingLevel: 3, paragraphs: ["Windows includes Storage Sense to help remove unnecessary temporary files and manage selected cleanup tasks. Be careful with the Recycle Bin, Downloads folder, and cloud-synced files. Review the settings before allowing automated deletion. Storage Sense primarily manages the Windows system drive; other drives may require separate cleanup. Do not delete unfamiliar Windows folders manually."], orderedList: ["Open Settings → System → Storage.", "Select Storage Sense.", "Review the cleanup settings.", "Enable the options appropriate for your needs."] },
    { heading: "4. Check CPU, memory, and disk usage", paragraphs: ["Task Manager is one of the most useful built-in tools for identifying performance bottlenecks. Press Ctrl + Shift + Esc and open the Processes tab. You can sort applications by CPU, Memory, or Disk usage.", "High CPU usage can indicate intensive tasks, background jobs, or a malfunctioning application. High memory usage can mean too many browser tabs or applications are competing for RAM. High disk activity can be caused by Windows Update, file syncing, antivirus scanning, or storage limitations.", "Identify the responsible process and decide whether its activity is expected. Close unnecessary user applications only after saving your work. Do not end processes simply because their names are unfamiliar; ending essential Windows components can cause instability."] },
    { heading: "5. Install Windows updates", paragraphs: ["Windows updates can include security fixes, reliability improvements, and compatibility changes. Some optional driver updates may also appear through Windows Update. If your computer belongs to an organization, follow its IT update policy rather than changing managed settings.", "Windows 10 users: Standard Windows 10 support ended on October 14, 2025. Eligible devices should move to a supported Windows 11 version. Devices that cannot upgrade may have Extended Security Updates options, subject to Microsoft's eligibility and enrollment terms. An unsupported Windows version is a security concern even if its performance seems acceptable."], orderedList: ["Open Settings.", "Select Windows Update.", "Click Check for updates.", "Install relevant available updates.", "Restart when required."] },
    { heading: "6. Scan for malware", paragraphs: ["Malware and unwanted software can affect performance, stability, and security. Windows Security includes Microsoft Defender Antivirus on supported Windows configurations. Keep antivirus definitions and Windows security protections updated. Avoid installing multiple antivirus products simultaneously without understanding their compatibility; conflicting real-time protection tools can create additional problems."], orderedList: ["Open Start and search for Windows Security.", "Select Virus & threat protection.", "Open Scan options, if available.", "Run an appropriate scan."], blockquote: "A quick scan is a reasonable first step. If you suspect malware or unexplained activity persists, consider a more thorough scan." },
    { heading: "7. Adjust Windows visual effects", paragraphs: ["Windows uses animations, shadows, and other effects to make the interface look polished. On older or low-powered systems, reducing some effects may improve perceived responsiveness. Modern, capable PCs may show little noticeable difference."], orderedList: ["Open Start.", "Search for Adjust the appearance and performance of Windows.", "Open the result.", "Select the Visual Effects tab.", "Choose Adjust for best performance, or customize individual options.", "Apply the changes."], blockquote: "This reduces visual polish, so you may prefer enabling selected effects again after testing." },
    { heading: "8. Review your power mode", paragraphs: ["Windows power settings balance performance, battery life, heat, and energy consumption. A laptop may behave differently on battery power compared with a charger. Open Settings → System → Power & battery and find the available Power mode setting.", "If supported, try Best performance while connected to power and observe whether your specific workload improves. This setting can increase energy consumption, heat, and fan activity. It is not always appropriate for battery-powered use, and the exact options depend on the device. If a laptop is unexpectedly throttling, also check the manufacturer's power and thermal management software."] },
    { heading: "9. Optimize your storage drives correctly", paragraphs: ["Windows includes a built-in drive optimization tool, but optimization differs by storage hardware. A traditional HDD can benefit from file defragmentation under appropriate conditions; an SSD uses different maintenance mechanisms, including TRIM. Windows usually performs drive optimization automatically."], orderedList: ["Search for Defragment and Optimize Drives.", "Open the Windows utility.", "Select your drive.", "Review the media type and optimization status.", "Use the built-in optimization option if needed."], blockquote: "Do not use third-party tools that force traditional hard-drive defragmentation procedures on SSDs. A drive with errors, unusual noises, or signs of hardware failure needs diagnostics rather than repeated optimization." },
    { heading: "10. Reduce browser memory usage", paragraphs: ["For many people, the browser is one of the largest consumers of system resources. Numerous tabs, demanding websites, browser extensions, and background applications can contribute to sluggish performance."], list: ["Close tabs you no longer need.", "Remove extensions you don't recognize or use.", "Keep the browser updated.", "Review built-in memory-saving features where available.", "Test performance in a clean browser profile.", "Check whether a particular website consistently causes the slowdown."], blockquote: "Avoid clearing all browsing data as your first troubleshooting step. It can sign you out or remove stored information without addressing the underlying performance issue." },
    { heading: "11. Check temperature and ventilation", paragraphs: ["A computer that becomes slow after running for a while may be experiencing thermal limitations. Processors and graphics hardware can reduce operating speeds when temperatures become too high. Warning signs include unusually high fan speeds, excessive laptop heat, slowdowns during intensive work, unexpected shutdowns, and performance dropping after sustained workloads."], list: ["Place a laptop on a firm, flat surface and keep vents unobstructed.", "Remove visible dust from accessible external vents using manufacturer-approved methods.", "Avoid opening a device or disconnecting cooling components unless you have the necessary knowledge and equipment.", "If a laptop shows battery swelling, stop using or charging it and seek qualified service."], blockquote: "Thermal issues can require professional cleaning or hardware repair." },
    { heading: "12. Consider hardware upgrades when software fixes aren't enough", paragraphs: ["Not every slow computer can be fixed through Windows settings. Older hardware can struggle with modern applications and multitasking.", "Upgrade from an HDD to an SSD: a compatible SSD may substantially improve startup and application loading. Back up data and confirm device support before upgrading.", "Increase RAM: additional memory may help when the system regularly exhausts available RAM, but it will not solve every problem and some laptops have soldered memory that cannot be upgraded."], blockquote: "Best approach: Identify the actual bottleneck before spending money on components." },
    { heading: "What if your Windows PC is still slow?", paragraphs: ["If you have tried the appropriate steps and performance remains poor, investigate more systematically.", "If the computer crashes, displays repeated disk errors, or cannot install updates, back up your files before attempting advanced repairs. Use the manufacturer's diagnostic utilities or a qualified technician where necessary. A complete Windows reset should be a last resort, not the first performance tip. Resetting or reinstalling Windows can remove applications and settings and may require careful data recovery planning."], list: ["Windows version and build.", "Processor model.", "Installed RAM.", "Storage type and free space.", "Which activities cause slowdowns.", "Whether the problem occurs after startup or only under load.", "Any recent software, driver, or hardware changes."] },
    { heading: "Common Windows speed-up myths", paragraphs: ["Myth 1: Registry cleaners always make Windows faster. Registry-cleaning software is not a reliable general-purpose performance solution; deleting registry entries can introduce problems without fixing the actual cause of slowdowns.", "Myth 2: Higher RAM usage always means something is wrong. Windows uses available memory for caching and other useful tasks; high usage matters more when accompanied by slowdowns, excessive paging, or applications running out of memory.", "Myth 3: You should disable as many Windows services as possible. Disabling unfamiliar services can break updates, device functions, networking, and security features. Troubleshoot specific processes instead.", "Myth 4: Every SSD needs manual defragmentation. SSDs are maintained differently from HDDs, and Windows' built-in optimization tools handle those differences.", "Myth 5: More optimization software means better performance. Adding background utilities may increase resource usage and system complexity; built-in Windows tools are often sufficient for initial diagnosis and maintenance."] },
    { heading: "Frequently asked questions", paragraphs: ["Why is my Windows 11 PC suddenly very slow? Possible causes include background updates, resource-heavy applications, insufficient storage, malware, or hardware issues. Check Task Manager and recent changes before making major adjustments.", "How do I speed up Windows 11 for free? Start with a restart, remove unnecessary startup applications, review storage usage, install updates, scan for malware, and identify resource-heavy processes.", "Does disabling startup apps make a PC faster? It can improve startup speed and reduce background resource usage, particularly when many unnecessary programs launch at sign-in.", "Does adding more RAM make Windows faster? It can improve multitasking when insufficient memory is the bottleneck, but may make little difference for a slow drive, overheating, or another limitation.", "Will an SSD improve an old laptop? Replacing a mechanical system drive with a compatible SSD can improve startup and application loading; the benefit depends on current hardware and usage.", "Should I still use Windows 10 in 2026? Standard support ended in October 2025. Microsoft recommends supported Windows 11 hardware where possible; Extended Security Updates are temporary rather than a long-term replacement.", "Should I reinstall Windows if my computer is slow? Not immediately. Identify the bottleneck and try targeted, low-risk fixes first; reinstall only after serious software troubleshooting fails and a reliable backup exists."] },
    { heading: "Final thoughts", paragraphs: ["Improving Windows performance is not about applying every optimization tip you can find. It is about identifying what is making your particular computer slow.", "Start with the basics: restart Windows, review startup programs, free up storage, update the operating system, and check Task Manager. If those steps don't help, examine memory pressure, drive health, browser activity, temperature, and hardware limitations.", "Most importantly, avoid tools that promise instant speed increases without explaining what they change. A systematic approach is safer, easier to evaluate, and more likely to address the underlying problem."] },
    { heading: "Editorial methodology", paragraphs: ["This guide was researched using Microsoft's official Windows support documentation and reviewed on October 9, 2026.", "Instructions primarily target Windows 11. Available menus and settings may differ depending on hardware, installed Windows version, device management policies, and future software updates.", "No proprietary performance benchmarks, measured speed improvements, or hands-on test results are claimed."] },
  ],
  codingTools: [
    { heading: "Build a small toolchain around the work", paragraphs: ["A productive developer setup usually needs an editor, version control, a runtime or compiler, dependency management, formatting or linting, tests, and a debugger. The right choices depend on language, team policy, target platform, and repository requirements. A free tool is not automatically low-cost if it adds maintenance, security review, or incompatible configuration."], list: ["Use the repository's documented runtime and package manager.", "Turn on the team's formatter and linter before making broad changes.", "Keep source control history readable with focused commits.", "Prefer built-in tools before adding extensions."] },
    { heading: "Evaluate tools with a real project", paragraphs: ["Try an editor or extension in a disposable branch on a representative repository. Verify language support, debugging, test integration, remote-development needs, accessibility, telemetry settings, update policy, and licence. Visual Studio Code's documentation describes editor features and extension management, but individual extensions are independently maintained and need their own review."], code: "# Before adding a tool, capture the baseline\nnode --version\nnpm --version\ngit status --short" },
    { heading: "Keep the setup maintainable", paragraphs: ["Pin project dependencies in the repository rather than relying on a personal global setup. Document required extensions and commands in the README, review permissions before installing extensions, and remove tools that duplicate existing capability. A smaller documented toolchain is easier for a new contributor to reproduce."], blockquote: "Choose tools that improve a repeatable workflow, not tools that merely add options." },
  ],
  rag: [
    { heading: "RAG connects a model to selected context", paragraphs: ["Retrieval-augmented generation (RAG) is a pattern in which an application retrieves relevant material and sends that material with the user's question to a language model. It does not retrain the model on every document. Microsoft Learn describes common implementations that prepare data, split it into chunks, create embeddings, retrieve relevant chunks, and then generate a response using that context."], list: ["Choose authoritative source documents.", "Extract and clean text with ownership and access controls.", "Chunk material so retrieval can return focused context.", "Retrieve, cite, evaluate, and monitor answers."] },
    { heading: "A practical support example", paragraphs: ["Imagine a support assistant for an internal product manual. When a user asks how to reset a setting, the system should retrieve the current manual section, identify the version, and show the source link alongside a concise answer. If retrieval finds weak or conflicting evidence, the assistant should say so or hand the question to support instead of filling gaps with confidence."], code: "question -> retrieve approved passages -> rank -> answer with citations\n                         |\n                         -> low confidence: ask for clarification or escalate" },
    { heading: "Limitations to design for", paragraphs: ["RAG can improve grounding, but it cannot make a weak document set correct, current, or safe. Retrieval can miss relevant material; a model can still misread supplied context; and permission boundaries matter as much as relevance. Test with known questions, measure citation quality, log failures safely, and give content owners a way to update the knowledge base."], blockquote: "Retrieval quality and source governance are product requirements, not implementation details." },
  ],
  security: [
    { heading: "Make account takeovers harder", paragraphs: ["Start with the accounts that can reset other accounts or expose money, identity documents, work systems, or personal messages. Use a different password for every account; a password manager can generate and store those passwords. NIST guidance discusses password managers, multi-factor authentication, and the risks created when credentials are reused."], list: ["Secure your primary email account first.", "Use unique passwords instead of variations on one password.", "Turn on multi-factor authentication where it is offered.", "Save recovery codes in a safe place that is not the same inbox you are protecting."] },
    { heading: "Prefer phishing-resistant options when available", paragraphs: ["Not every second factor offers the same protection. NIST describes phishing-resistant authentication as preventing an attacker posing as a service from obtaining a usable authenticator output; WebAuthn-based authenticators are an example of verifier name binding. Check whether a service supports passkeys or security keys, then follow that service's recovery guidance before removing an existing sign-in method."], list: ["Verify the site address before entering a password or approval code.", "Treat unexpected login prompts and recovery messages as suspicious.", "Review active sessions and recovery methods after a suspected compromise.", "Contact the service through its known support path, not a link in an unsolicited message."] },
    { heading: "Have a recovery plan", paragraphs: ["Record which accounts use which recovery channels. If you think an account was taken over, change the password from a trusted device, revoke unfamiliar sessions, review forwarding rules and payment details, and use the provider's documented recovery process. This is general information; high-risk accounts or an active incident may need specialist help."], blockquote: "The recovery email account deserves the strongest protection in your account set." },
  ],
  vscode: [
    { heading: "Choose extensions for a specific gap", paragraphs: ["Extensions can add language support, linting, formatting, test integration, source control views, and other workflow features. Start with the extension recommendations documented by the project's maintainers, then use the Visual Studio Code Marketplace and extension documentation to verify publisher, permissions, compatibility, update cadence, and privacy details."], list: ["Install one extension to solve one identified problem.", "Read the publisher and repository information.", "Check Workspace Trust and extension permissions.", "Test in a non-critical workspace before adopting it team-wide."] },
    { heading: "A sensible starter checklist", paragraphs: ["For many projects, the useful categories are language support, a formatter, a linter, test integration, and version-control assistance. The specific extension names should come from the project's stack and its current documentation, not from a generic list. An extension that conflicts with a repository's formatter or adds overlapping automation can create more noise than value."], code: "# Record team-required extensions in the repository\ncode --list-extensions\n# Review the output before copying it into documentation" },
    { heading: "Keep the editor trustworthy", paragraphs: ["Update VS Code and extensions regularly, disable unused extensions, and use Workspace Trust for unfamiliar repositories. Review an extension after a major update or ownership change. This article is a selection guide, not an endorsement or security assessment of a particular extension."], blockquote: "The best extension is one the team can explain, reproduce, and maintain." },
  ],
  hosting: [
    { heading: "Define the workload before comparing plans", paragraphs: ["A hosting choice starts with the site: static files, a server-rendered app, a database-backed service, or a mix. Write down expected traffic patterns, required regions, runtime version, build time, storage, backups, deployment workflow, support needs, and spending limits. Without those constraints, a provider comparison becomes a list of marketing claims."], list: ["Which parts of the site need a server at request time?", "Where are visitors and data located?", "What is the rollback and backup plan?", "Who will respond to an outage or failed deploy?"] },
    { heading: "Compare the operational details", paragraphs: ["Read each provider's current pricing, service limits, support policy, documentation, and terms. Check what happens when traffic spikes, a build fails, a limit is exceeded, or a dependency needs an update. For a Next.js site, verify supported Node and framework versions, image handling, environment-variable controls, logs, redirects, caching, and deployment preview workflow."], list: ["Use a staging or preview deployment before moving a production domain.", "Test a rollback rather than assuming one exists.", "Price the expected workload and a higher-traffic scenario.", "Document account ownership and recovery contacts."] },
    { heading: "Avoid irreversible decisions", paragraphs: ["Keep the domain, source repository, content exports, and environment-variable inventory under the publisher's control. Prefer a deployment process that another team member can reproduce. This guide does not recommend a provider because suitability depends on the verified requirements above."], blockquote: "A cheap plan is expensive if no one can restore the site when it fails." },
  ],
  productivity: [
    { heading: "Choose a workflow before choosing an app", paragraphs: ["A productivity app is useful when it supports a small repeatable practice: capture work, decide what matters, schedule or sequence it, and review commitments. Before comparing products, write down where tasks enter your system, who shares them, which devices matter, and what information must stay private. A feature list cannot decide those questions for you."], list: ["Capture new work in one dependable place.", "Separate a next action from a vague project idea.", "Review commitments on a regular cadence.", "Use notifications deliberately rather than leaving every alert on."] },
    { heading: "Test the smallest viable setup", paragraphs: ["Try a candidate app with a real week of work, not an empty demo. Add recurring obligations, a project with several steps, a shared request if collaboration matters, and one interruption. Measure whether the system makes the next action clearer. If it creates duplicate lists or demands constant restructuring, simplify before migrating more information."], code: "Weekly review\n1. Clear inboxes\n2. Confirm deadlines\n3. Choose next actions\n4. Remove stale tasks\n5. Plan focused time" },
    { heading: "Protect portability and attention", paragraphs: ["Check export options, account recovery, offline behaviour, device support, sharing controls, pricing, and data policy before committing important work. The best app is often the one your team will still use after the novelty fades. This is a decision framework, not a ranked product review."], blockquote: "A system you review consistently is more valuable than a feature-rich system you avoid." },
  ],
  apis: [
    { heading: "An API is an agreed interface", paragraphs: ["An application programming interface defines how one piece of software can ask another for a capability or data. MDN describes APIs as constructs that make complex functionality easier to use by exposing an interface instead of every implementation detail. On the web, an HTTP API commonly receives a request and returns a response with a status code, headers, and a body."], code: "GET /api/articles/42 HTTP/1.1\nAccept: application/json\n\nHTTP/1.1 200 OK\nContent-Type: application/json\n\n{ \"id\": 42, \"title\": \"Example\" }" },
    { heading: "Follow one request from start to finish", paragraphs: ["A client first chooses an endpoint and method, then sends required parameters and authentication. The server validates the request, performs the allowed work, and returns a success or error response. A useful API client handles both expected results and failures: invalid input, missing permission, rate limits, timeouts, and unavailable services."], list: ["Use HTTPS and keep secrets out of browser code.", "Read the endpoint's authentication and rate-limit rules.", "Check status codes before assuming a JSON body is successful.", "Log safe diagnostic context, never credentials or personal data."] },
    { heading: "Build a safe first integration", paragraphs: ["Start with a read-only endpoint in a test environment. Store secrets in the platform's environment-variable system, use the vendor's documented SDK or HTTP specification, and add timeouts and clear error messages. Webhooks are different: your application receives an event, so verify signatures and design processing to tolerate retries and duplicate deliveries."], blockquote: "An integration is complete only when its error and security paths are designed too." },
  ],
  wordpress: [
    { heading: "Make the problem reproducible before changing the site", paragraphs: ["WordPress errors can come from plugins, themes, caching, server configuration, updates, permissions, or a service outside WordPress. Record the exact message, URL, time, recent changes, affected users, and browser/device. Take a current backup and confirm how to restore it before disabling or updating anything on a production site."], list: ["Check the site's status and recent update history.", "Reproduce the issue in a private browser window if appropriate.", "Review error logs through the host or WordPress debugging process.", "Make one change at a time and record the result."] },
    { heading: "Isolate plugins and themes safely", paragraphs: ["WordPress's troubleshooting documentation recommends controlled isolation of plugins and themes. Prefer a staging site or maintenance window for a production property. If disabling a plugin resolves the issue, update, replace, or contact its maintainer rather than immediately reinstalling WordPress. Preserve settings and data before removing an extension."], code: "# Do not run this on production without a backup and maintenance plan.\n# Use your host's staging environment to test plugin/theme changes first." },
    { heading: "Prevent recurring incidents", paragraphs: ["Keep WordPress core, themes, plugins, PHP, and backups on a documented maintenance schedule. Limit administrator accounts and unused plugins, use trusted sources, and test updates on staging when the site is important. If an error involves payment, personal data, malware, or server compromise, use the host's incident process or qualified support."], blockquote: "A backup is useful only when restoration has been tested." },
  ],
  aiSoftware: [
    { heading: "Look for workflow changes, not slogans", paragraphs: ["AI features can change how software helps users search, draft, classify, summarise, and automate routine steps. That does not mean every feature improves a product. Product teams need to identify the user decision or task, define acceptable error rates, and design a human fallback. A generated answer that sounds convincing can still be incomplete or wrong."], list: ["Choose a narrow user problem.", "Decide which inputs are permitted.", "Define review, correction, and escalation paths.", "Measure outcomes that matter to users, not only model output volume."] },
    { heading: "Design for evidence and control", paragraphs: ["For high-impact workflows, show relevant source material, make uncertainty visible, and let users correct or reject output. Keep an audit trail appropriate to the risk, protect sensitive data, and test the system with edge cases. OpenAI and Anthropic both publish product documentation, but product capabilities, controls, and limits change; teams should verify the current documentation for the exact service and plan they use."], code: "User request -> policy check -> retrieve approved context -> draft output\n                                      |\n                                      -> cite, review, correct, or escalate" },
    { heading: "What developers can contribute", paragraphs: ["Developers can make AI features more dependable by defining interfaces, evaluation cases, monitoring, access controls, rate limits, and fallbacks. The durable work is not just prompting: it is product judgment, data governance, reliability, and user experience. This article is an engineering framework, not a forecast or a claim about industry-wide adoption."], blockquote: "Useful AI software makes the next responsible action clearer." },
  ],
};

/** Product names below are examples to evaluate, never rankings or claimed tests. */
export const editorialExpansions: Record<string, ArticleSection[]> = {
  windows: [
    { heading: "Work through the Windows checks in order", paragraphs: ["First, save work and restart. Then open Settings > Windows Update and install available updates; Microsoft also documents optional driver updates in Windows Update. Next, open Windows Security > Virus & threat protection and run a scan. Finally, open Settings > System > Storage, review temporary files, and use Storage Sense only after checking what will be removed."], list: ["Record free disk space before and after cleanup.", "Use Task Manager's Processes tab while the slowdown is happening, rather than guessing which app is responsible.", "In Startup apps, disable only recognised non-essential apps and restart to test.", "If a recent app or driver coincides with the issue, use the vendor's documented uninstall or rollback path."] },
    { heading: "Avoid common false fixes", paragraphs: ["Do not install registry cleaners, driver-updater bundles, or ‘RAM boosters’ because an advert promises a speed increase. Do not manually defragment an SSD. If diagnostics show persistent hardware symptoms, back up data and use the device maker's support path rather than repeatedly changing Windows settings."], links: [{ label: "Protect online accounts after a suspicious download", href: "/article/how-to-protect-your-online-accounts" }] },
  ],
  codingTools: [
    { heading: "A concrete free baseline", paragraphs: ["A conventional starting point is Visual Studio Code for editing, Git for version control, the runtime named by the repository, and project-local commands for formatting, linting, testing, and debugging. ESLint and Prettier are examples of tools a JavaScript project may already use; do not add them just because another project does. The repository's package manifest and contributor documentation are the source of truth."], list: ["Editor: use a maintained editor with language support for the project.", "Version control: use Git and the repository's review workflow.", "Quality checks: run the project's formatter, linter, type check, and tests.", "Debugging: start with the runtime and framework's built-in tools before adding a GUI client."] },
    { heading: "Check before installing", paragraphs: ["Read the licence, publisher, permissions, update policy, and maintenance status for any extension or desktop client. Keep a note of why it was introduced and how to remove it. This avoids turning a personal preference into an undocumented team dependency."], links: [{ label: "Choosing VS Code extensions responsibly", href: "/article/best-vscode-extensions-for-developers" }, { label: "A beginner's guide to APIs", href: "/article/beginners-guide-to-apis" }] },
  ],
  rag: [
    { heading: "Build the retrieval path deliberately", paragraphs: ["A useful RAG design usually has four separate concerns: ingest approved documents, split and index them, retrieve and rank candidates for a question, and generate an answer that identifies the evidence used. Microsoft describes chunking and embeddings as common indexing steps; the exact implementation depends on the data, query patterns, and access model."], list: ["Attach source, version, owner, and permission metadata to each chunk.", "Test retrieval independently from answer writing.", "Return a source link or passage identifier when the product can safely do so.", "Set a fallback for weak evidence instead of forcing an answer."] },
    { heading: "Evaluate with questions that have known answers", paragraphs: ["Create a small evaluation set from current approved documents. Include answerable questions, ambiguous questions, questions that should be refused for access reasons, and questions where the material is missing. Review retrieved passages as well as the final response; a fluent answer is not evidence that retrieval worked."], links: [{ label: "Comparing AI assistants without a universal winner", href: "/article/chatgpt-vs-claude" }, { label: "How AI affects software design work", href: "/article/how-ai-is-changing-software-development" }] },
  ],
  security: [
    { heading: "A practical account-hardening order", paragraphs: ["Start with the email inbox used for password resets, then financial, work, cloud-storage, and messaging accounts. Use a password manager to create a distinct password for each account. Enable the strongest sign-in method that the service actually offers and make sure recovery codes and recovery contacts are current before removing an old method."], list: ["Check recovery email addresses and phone numbers.", "Remove sessions and devices you do not recognise.", "Turn on alerts for sign-ins or security changes where available.", "Store recovery codes away from the account they recover."] },
    { heading: "Treat a suspected compromise as an incident", paragraphs: ["Use a trusted device, change the affected password, revoke unfamiliar sessions, inspect forwarding rules and payment details, and follow the provider's own recovery process. Never give a one-time code to someone who contacted you unexpectedly. For a work or financial account, report the incident through the organisation or institution's known channel."], links: [{ label: "Safe WordPress troubleshooting", href: "/article/common-wordpress-errors-and-fixes" }] },
  ],
  vscode: [
    { heading: "Useful categories and examples to investigate", paragraphs: ["The most useful extensions depend on the language and repository. For a JavaScript or TypeScript project, developers often evaluate ESLint (`dbaeumer.vscode-eslint`) for lint feedback and Prettier (`esbenp.prettier-vscode`) for formatting. GitLens (`eamodio.gitlens`) is an example of an optional source-control extension. These names are examples to investigate in the Marketplace, not endorsements or a security review."], list: ["Confirm the publisher and read the Marketplace README and changelog.", "Check whether the repository already owns formatting and linting configuration.", "Install one extension at a time and test it in a non-critical workspace.", "Remove overlapping extensions when they create competing edits or notifications."] },
    { heading: "Use workspace recommendations sparingly", paragraphs: ["VS Code supports workspace extension recommendations, which can help a team document genuinely required tooling. Keep the list short and explain why each extension is needed. An individual developer can still use a personal profile for optional preferences without making that preference a project requirement."], code: "// .vscode/extensions.json\n{\n  \"recommendations\": [\"dbaeumer.vscode-eslint\"]\n}", links: [{ label: "Build a maintainable free coding toolchain", href: "/article/best-free-coding-tools" }] },
  ],
  hosting: [
    { heading: "Compare hosting models before vendors", paragraphs: ["A static site host, a managed Next.js platform, a managed WordPress host, and a general cloud provider solve different operational problems. For a Next.js application, verify Node and framework support, server-rendering needs, image handling, environment-variable controls, logs, redirects, preview deployments, and rollback procedures. For a WordPress site, confirm staging, backups, update controls, and support boundaries."], list: ["Static or mostly static site: ask about deploy previews, cache invalidation, and image delivery.", "Server-rendered app: ask about runtime limits, logs, scaling, and incident support.", "CMS site: ask about backups, staging, PHP/database compatibility, and update recovery.", "Every model: keep domain and account recovery under the publisher's control."] },
    { heading: "Run a reversible proof of concept", paragraphs: ["Use a preview or staging deployment, set only non-production environment values, deploy a small representative build, and test a rollback. Compare the provider's documented limits and current billing terms against measured build time, traffic, storage, and support needs. Do not move a production domain until those checks pass."], links: [{ label: "WordPress troubleshooting and maintenance", href: "/article/common-wordpress-errors-and-fixes" }] },
  ],
  productivity: [
    { heading: "Match an app to the shape of the work", paragraphs: ["Todoist is worth evaluating when an individual or small team needs tasks, projects, reminders, filters, and collaboration. Notion is worth evaluating when tasks need to live alongside documents and a custom project database. Neither is automatically better: compare capture speed, recurring work, collaboration, notifications, export, recovery, offline behaviour, accessibility, pricing, and data controls for your own workflow."], list: ["Personal action list: test whether new tasks are quick to capture and review.", "Shared work: test assignment, permission, comments, and hand-off clarity.", "Documentation-heavy work: test whether project context remains findable without duplicating it.", "Migration: export a small trial project before committing important work."] },
    { heading: "Run a one-week trial with an exit test", paragraphs: ["Use a real week of low-risk work and keep a simple tally: tasks captured, tasks lost, duplicated lists, unexpected notifications, and time spent maintaining the system. At the end, test export and account recovery documentation. This article does not rank apps or make a claim about current plan features; verify vendors' current help and pricing pages before choosing."], links: [{ label: "Choose a web host with a reversible trial", href: "/article/how-to-choose-a-web-hosting-provider" }, { label: "Build a lean coding workflow", href: "/article/best-free-coding-tools" }] },
  ],
  apis: [
    { heading: "Try a safe read-only request", paragraphs: ["Before adding authentication or writes, call a documented read-only endpoint in a test environment. Read the response status before parsing the body, set a timeout in the real application, and show an error that helps the user without revealing credentials. The following example illustrates the control flow; endpoint and authentication details always come from the provider's documentation."], code: "const response = await fetch(\"https://api.example.test/articles/42\");\nif (!response.ok) {\n  throw new Error(`Request failed: ${response.status}`);\n}\nconst article = await response.json();" },
    { heading: "Keep credentials and webhooks separate from browser code", paragraphs: ["A browser bundle is not a safe place for a secret API key. Put secrets in server-side environment configuration, grant only the permissions needed, and rotate or revoke a key through the provider when necessary. For webhooks, verify the provider's signature and make handlers safe to retry because delivery can be duplicated or delayed."], links: [{ label: "Build a dependable developer toolchain", href: "/article/best-free-coding-tools" }, { label: "Understand RAG application architecture", href: "/article/what-is-retrieval-augmented-generation" }] },
  ],
  wordpress: [
    { heading: "A safe procedure for a plugin or theme conflict", paragraphs: ["Do this on staging whenever possible. First take and verify a backup. Record the error, time, affected URL, and recent changes. If the dashboard is available, temporarily deactivate plugins, then reactivate them one at a time while checking the same symptom. If the problem disappears only with a default theme, document that result before contacting the theme or plugin maintainer."], list: ["Do not delete a plugin before preserving its settings and data.", "Do not test broad deactivation on a busy production store without a maintenance plan.", "Check browser console and network errors when a front-end action fails.", "Use the host's logs and WordPress Site Health information to collect evidence."] },
    { heading: "Turn a repair into a maintenance record", paragraphs: ["Write down the cause, versions, change made, rollback method, and result. Keep core, themes, plugins, PHP, and backups on an owned maintenance schedule; test updates on staging when the site matters. A white screen, a payment issue, suspected malware, or personal-data exposure should go through the host's or security provider's incident process rather than an improvised fix."], links: [{ label: "Choose a hosting provider by operational evidence", href: "/article/how-to-choose-a-web-hosting-provider" }, { label: "Protect accounts used for WordPress administration", href: "/article/how-to-protect-your-online-accounts" }] },
  ],
  aiSoftware: [
    { heading: "Where AI changes software work", paragraphs: ["AI can assist with narrow activities such as drafting text, classifying incoming work, retrieving approved knowledge, and generating a first implementation outline. The engineering question is not whether output exists; it is whether the product makes errors visible, protects permitted data, and gives a user a safe correction or escalation path."], list: ["Define the task and an unacceptable failure before choosing a model.", "Keep the source or reason for an important output visible where practical.", "Measure correction effort and harmful failures, not only how much text was generated.", "Retain a non-AI path for outages, uncertainty, or user preference where the risk warrants it."] },
    { heading: "Make evaluation part of delivery", paragraphs: ["Before release, create representative examples with expected outcomes, include edge cases and refusals, and review results whenever a model, prompt, tool, or data source changes. Product teams should record what was evaluated and what was not. This is more useful to readers than a broad prediction about which companies will ‘win’."], links: [{ label: "A practical introduction to RAG", href: "/article/what-is-retrieval-augmented-generation" }, { label: "How to compare assistants responsibly", href: "/article/chatgpt-vs-claude" }] },
  ],
};
